[package]
name = "pcap"
version = "0.1.0"
edition = "2021"

[dependencies]
#[cfg(target_os = "windows")]
#winapi = { version = "0.3.9", features = ["winsock2", "ws2tcpip", "winnt", "iphlpapi"] }

[lib]
name = "pcap"
path = "src/lib.rs"
